//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoteloProjectFramework.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntidadesSotelo : DbContext
    {
        public EntidadesSotelo()
            : base("name=EntidadesSotelo")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<cBuzonEstatus> cBuzonEstatus { get; set; }
        public virtual DbSet<cMenus> cMenus { get; set; }
        public virtual DbSet<cRecursosGenerales> cRecursosGenerales { get; set; }
        public virtual DbSet<tbBuzon> tbBuzon { get; set; }
        public virtual DbSet<tbCategoriasChoferes> tbCategoriasChoferes { get; set; }
        public virtual DbSet<tbChoferes> tbChoferes { get; set; }
        public virtual DbSet<tbContabilidadViaje> tbContabilidadViaje { get; set; }
        public virtual DbSet<tbDetallesChoferes> tbDetallesChoferes { get; set; }
        public virtual DbSet<tbMenusRoles> tbMenusRoles { get; set; }
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }
        public virtual DbSet<tbViajes> tbViajes { get; set; }
    }
}
