//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoteloProjectFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBuzon
    {
        public int BuzonId { get; set; }
        public int BuzonEstatusId { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public string Asunto { get; set; }
        public bool Estatus { get; set; }
        public bool Eliminado { get; set; }
    
        public virtual cBuzonEstatus cBuzonEstatus { get; set; }
    }
}
