//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoteloProjectFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbContabilidadViaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbContabilidadViaje()
        {
            this.tbViajes = new HashSet<tbViajes>();
        }
    
        public int ContabilidadViajeId { get; set; }
        public Nullable<decimal> Diesel { get; set; }
        public decimal Importe { get; set; }
        public decimal SalarioBrutoChofer { get; set; }
        public decimal Gastos { get; set; }
        public decimal SalarioNeto { get; set; }
        public decimal Ganancia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbViajes> tbViajes { get; set; }
    }
}
