//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoteloProjectFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbUsuarios()
        {
            this.tbMenusRoles = new HashSet<tbMenusRoles>();
        }
    
        public int UsuarioId { get; set; }
        public System.Guid Guid { get; set; }
        public string RolId { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string Nombres { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Email { get; set; }
        public string Contrasenia { get; set; }
        public string FotoBase64 { get; set; }
        public bool Estatus { get; set; }
        public bool Eliminado { get; set; }
        public string UsuarioElimino { get; set; }
        public Nullable<System.DateTime> FechaElimino { get; set; }
        public string MotivoElimino { get; set; }
    
        public virtual AspNetRoles AspNetRoles { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMenusRoles> tbMenusRoles { get; set; }
    }
}
