//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoteloProjectFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbViajes
    {
        public int ViajeId { get; set; }
        public int ChoferId { get; set; }
        public int ContabilidadViajeId { get; set; }
        public string Folio { get; set; }
        public System.DateTime Fecha { get; set; }
        public string FechaStr { get; set; }
        public string LugarOrigen { get; set; }
        public string LugarDestino { get; set; }
    
        public virtual tbChoferes tbChoferes { get; set; }
        public virtual tbContabilidadViaje tbContabilidadViaje { get; set; }
    }
}
